## YAML Template.
---
logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: TRACE
#    org.springframework.boot.autoconfigure: DEBUG

server:
  port: 8081
  
spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/jwt
    username: cge
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

#  security:
#    user:
#      password: pass1234

  jackson:
    serialization:
        FAIL_ON_EMPTY_BEANS: false
    
    
#jwt:
#  private.key: classpath:app.key
#  public.key: classpath:app.pub 